### ISSUE TITLE
Cannot create property 'pos' on string 'T'

### ISSUE THREAD

**Issue by AndyGura** [giniedp/webidl2ts#17]
When trying to run command from readme

```webidl2ts -e -i https://raw.githubusercontent.com/kripken/ammo.js/master/ammo.idl -o ammo.d.ts```

I encounter this error. Full console output:

```
(node:277438) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
DeprecationWarning: 'createTypeReferenceNode' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createKeywordTypeNode' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createMethodSignature' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createClassDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createExpressionWithTypeArguments' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createHeritageClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createToken' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createPropertySignature' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createStringLiteral' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createLiteralTypeNode' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createUnionTypeNode' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createTypeAliasDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createModifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createTypeParameterDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:21342
        range.pos = pos;
                  ^

TypeError: Cannot create property 'pos' on string 'T'
    at setTextRangePos (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:21342:19)
    at Object.setTextRangePosEnd (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:21360:32)
    at createNodeArray (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:22985:16)
    at asNodeArray (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:27581:28)
    at createBaseNamedDeclaration (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:23009:34)
    at Object.createTypeParameterDeclaration (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:23450:24)
    at Object.createTypeParameterDeclaration (/usr/lib/node_modules/webidl2ts/node_modules/typescript/lib/typescript.js:3138:29)
    at Object.printEmscriptenModule (/usr/lib/node_modules/webidl2ts/dist/print-ts.js:36:30)
    at /usr/lib/node_modules/webidl2ts/dist/cli.js:126:47
    at step (/usr/lib/node_modules/webidl2ts/dist/cli.js:34:23)

Node.js v21.6.2
```

How shall I fix that? Thanks

**Comment by wxj0102** [comment]
另一个fork了一份 然后解决了这个问题
[https://github.com/pmndrs/webidl-dts-gen](https://github.com/pmndrs/webidl-dts-gen)

**Comment by giniedp** [comment]
@wxj0102 thank you for picking up the project and improving on it. I'm going to archive this project, in favor of yours

**Comment by AndyGura** [comment]
@giniedp can you please write it down to the readme and publish this announcement to npm please? There is no way people can find out they should migrate to different package right now. Thank you for your work!
